require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkoutLevelsController do

  # This should return the minimal set of attributes required to create a valid
  # WorkoutLevel. As you add validations to WorkoutLevel, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorkoutLevelsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all workout_levels as @workout_levels" do
      workout_level = WorkoutLevel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:workout_levels).should eq([workout_level])
    end
  end

  describe "GET show" do
    it "assigns the requested workout_level as @workout_level" do
      workout_level = WorkoutLevel.create! valid_attributes
      get :show, {:id => workout_level.to_param}, valid_session
      assigns(:workout_level).should eq(workout_level)
    end
  end

  describe "GET new" do
    it "assigns a new workout_level as @workout_level" do
      get :new, {}, valid_session
      assigns(:workout_level).should be_a_new(WorkoutLevel)
    end
  end

  describe "GET edit" do
    it "assigns the requested workout_level as @workout_level" do
      workout_level = WorkoutLevel.create! valid_attributes
      get :edit, {:id => workout_level.to_param}, valid_session
      assigns(:workout_level).should eq(workout_level)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WorkoutLevel" do
        expect {
          post :create, {:workout_level => valid_attributes}, valid_session
        }.to change(WorkoutLevel, :count).by(1)
      end

      it "assigns a newly created workout_level as @workout_level" do
        post :create, {:workout_level => valid_attributes}, valid_session
        assigns(:workout_level).should be_a(WorkoutLevel)
        assigns(:workout_level).should be_persisted
      end

      it "redirects to the created workout_level" do
        post :create, {:workout_level => valid_attributes}, valid_session
        response.should redirect_to(WorkoutLevel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved workout_level as @workout_level" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkoutLevel.any_instance.stub(:save).and_return(false)
        post :create, {:workout_level => {}}, valid_session
        assigns(:workout_level).should be_a_new(WorkoutLevel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkoutLevel.any_instance.stub(:save).and_return(false)
        post :create, {:workout_level => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested workout_level" do
        workout_level = WorkoutLevel.create! valid_attributes
        # Assuming there are no other workout_levels in the database, this
        # specifies that the WorkoutLevel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WorkoutLevel.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => workout_level.to_param, :workout_level => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested workout_level as @workout_level" do
        workout_level = WorkoutLevel.create! valid_attributes
        put :update, {:id => workout_level.to_param, :workout_level => valid_attributes}, valid_session
        assigns(:workout_level).should eq(workout_level)
      end

      it "redirects to the workout_level" do
        workout_level = WorkoutLevel.create! valid_attributes
        put :update, {:id => workout_level.to_param, :workout_level => valid_attributes}, valid_session
        response.should redirect_to(workout_level)
      end
    end

    describe "with invalid params" do
      it "assigns the workout_level as @workout_level" do
        workout_level = WorkoutLevel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkoutLevel.any_instance.stub(:save).and_return(false)
        put :update, {:id => workout_level.to_param, :workout_level => {}}, valid_session
        assigns(:workout_level).should eq(workout_level)
      end

      it "re-renders the 'edit' template" do
        workout_level = WorkoutLevel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkoutLevel.any_instance.stub(:save).and_return(false)
        put :update, {:id => workout_level.to_param, :workout_level => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested workout_level" do
      workout_level = WorkoutLevel.create! valid_attributes
      expect {
        delete :destroy, {:id => workout_level.to_param}, valid_session
      }.to change(WorkoutLevel, :count).by(-1)
    end

    it "redirects to the workout_levels list" do
      workout_level = WorkoutLevel.create! valid_attributes
      delete :destroy, {:id => workout_level.to_param}, valid_session
      response.should redirect_to(workout_levels_url)
    end
  end

end
